apiVersion: v2
name: designate-webhook
version: 1.0.0
appVersion: "1.0.0"
description: Allow cert-manager to solve DNS challenges using Openstack Designate DNS API V2
home: https://github.com/rikotsev/cert-manager-webhook-designate
icon: https://raw.githubusercontent.com/cert-manager/cert-manager/master/logo/logo-small.png
keywords:
  - cert-manager
  - designate
  - openstack
  - letsencrypt
  - tls
sources:
  - https://github.com/rikotsev/cert-manager-webhook-designate
maintainers:
  - name: rikotsev
    email: r.i.kotsev@gmail.com
annotations:
  artifacthub.io/license: Apache-2.0

